### ISSUE TITLE
new docs in tutorials not in tutorials-manifest?

### ISSUE THREAD

**Issue by horaceb** [SEL4PROJ/sel4-tutorials-manifest#1]
maybe this is normal release procedure.

**Comment by ikuz** [comment]
Hi,

I'm not sure what you mean by this.  

sel4-tutorials-manifest contains only the repo manifest files for the tutorial.  All the docs and code are in the sel4-tutorials

**Comment by horaceb** [comment]
Hi ikuz,

The file sel4-tutorials/docs/seL4-devices.pdf for example was added to the sel4-tutorials repo but when i do a "repo sync" in my local sel4-tutorials-manifest folder, it does not appear in the /sel4-tutorials-manifest/projects/sel4-tutorials/docs/ folder.

best

**Comment by ikuz** [comment]
Ah, I see.

Yes, the main manifests are fixed at specific released versions.

If you want the head then use the *-master.xml manifests.

Ihor.

**Comment by horaceb** [comment]
ok thanks
