### ISSUE TITLE
Camkes VM Linux tutorial

### ISSUE THREAD

**Issue by HediDlp** [SEL4PROJ/sel4-tutorials-manifest#3]
Hi,

After running ./init --plat pc99 --tut camkes-vm-linux(following https://docs.sel4.systems/Tutorials/camkes-vm-linux.html) following error will occurred:

 -- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/gcc
CMake Error at projects/camkes/vm/camkes_vm_helpers.cmake:21 (ApplyCommonReleaseVerificationSettings):
  ApplyCommonReleaseVerificationSettings Function invoked with incorrect
  arguments for function named: ApplyCommonReleaseVerificationSettings
Call Stack (most recent call first):
  camkes-vm-linux/CMakeLists.txt:10 (include)

-- camkes-gen.cmake is out of date. Regenerating...
-- Configuring incomplete, errors occurred!
See also "/home/hedi/sel4-tutorials-manifest/camkes-vm-linux_build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "./init", line 91, in <module>
  File "./init", line 81, in main
  File "/home/hedi/sel4-tutorials-manifest/projects/sel4-tutorials/common.py", line 107, in init_directories
    return _init_build_directory(config, initialised, build_directory, tute_directory, output, config_dict=config_dict)
  File "/home/hedi/sel4-tutorials-manifest/projects/sel4-tutorials/common.py", line 69, in _init_build_directory
    result = sh.cmake(args + ['..'], _cwd = directory, _out=output, _err=output)
  File "/home/hedi/.local/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/hedi/.local/lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/home/hedi/.local/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/hedi/.local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/cmake -DCMAKE_TOOLCHAIN_FILE=../kernel/gcc.cmake -G Ninja -DTUT_BOARD=pc -DTUT_ARCH=x86_64 -DFORCE_IOMMU=ON -DTUTORIAL_DIR=camkes-vm-linux ..

  STDOUT:

  STDERR:

Any Idea?

**Comment by WellMcGarnicle** [comment]
This issue has been discussed and fixed, see: http://sel4.systems/pipermail/devel/2018-October/002206.html

**Comment by HediDlp** [comment]
Dear Adam,

I have also another issue. After adding a kernel module as described in the
tutorial following error after running ninja has occored:

[1/28] Performing build step for 'hello-app'
ninja: no work to do.
[2/28] Performing build step for 'parse_capdl_tool'
make: Nothing to be done for 'all'.
[9/27] Performing configure step for 'poke-module'
FAILED: camkes-vm-linux/poke-module-stamp/poke-module-configure
cd
/home/hedi/sel4-tutorials-manifest/camkes-vm-linux_build/camkes-vm-linux/poke-module
&& /usr/bin/cmake -DCMAKE_BUILD_TYPE=Debug
-DCMAKE_TOOLCHAIN_FILE=/home/hedi/sel4-tutorials-manifest/tools/seL4/cmake-tool/polly_toolchains/linux-gcc-32bit-pic.cmake
-DLINUX_KERNEL_DIR=/home/hedi/sel4-tutorials-manifest/camkes-vm-linux_build/camkes-vm-linux/out/linux-4.8.16
-DMODULE_HELPERS_FILE=/home/hedi/sel4-tutorials-manifest/camkes-vm-linux/../projects/camkes/vm-linux/linux-module-helpers.cmake
-GNinja /home/hedi/sel4-tutorials-manifest/camkes-vm-linux/modules &&
/usr/bin/cmake -E touch
/home/hedi/sel4-tutorials-manifest/camkes-vm-linux_build/camkes-vm-linux/poke-module-stamp/poke-module-configure
-- [polly] Used toolchain: Linux / gcc / PIC / c++11 support / 32 bit
-- The CXX compiler identification is GNU 6.4.0
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45
(message):
  The C++ compiler

    "/usr/bin/g++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir:
/home/hedi/sel4-tutorials-manifest/camkes-vm-linux_build/camkes-vm-linux/poke-module/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/ninja" "cmTC_96725"
    [1/2] Building CXX object
CMakeFiles/cmTC_96725.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_96725
    FAILED: cmTC_96725
    : && /usr/bin/g++  -m32 -fPIC -std=c++11
CMakeFiles/cmTC_96725.dir/testCXXCompiler.cxx.o  -o cmTC_96725   && :
    /usr/bin/x86_64-linux-gnu-ld: skipping incompatible
/usr/lib/gcc/x86_64-linux-gnu/6/libstdc++.so when searching for -lstdc++
    /usr/bin/x86_64-linux-gnu-ld: skipping incompatible
/usr/lib/gcc/x86_64-linux-gnu/6/libstdc++.a when searching for -lstdc++
    /usr/bin/x86_64-linux-gnu-ld: cannot find -lstdc++
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt


-- Configuring incomplete, errors occurred!
See also
"/home/hedi/sel4-tutorials-manifest/camkes-vm-linux_build/camkes-vm-linux/poke-module/CMakeFiles/CMakeOutput.log".
See also
"/home/hedi/sel4-tutorials-manifest/camkes-vm-linux_build/camkes-vm-linux/poke-module/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

I installed both 32 and 64 bit version of libstdc++. Any sollution?

Best regards,
Hedi/
