### ISSUE TITLE
DTC

### ISSUE THREAD

**Issue by matthew-renodin** [SEL4PROJ/sel4-tutorials-manifest#4]
performed the following

mkdir sel4-tutorials-manifest
cd sel4-tutorials-manifest
repo init -u https://github.com/SEL4PROJ/sel4-tutorials-manifest
repo sync

mkdir threadStuff
cd threadStuff

../init --plat zynq7000 --tut threads --solution

CMake Error at kernel/src/arch/arm/config.cmake:108 (message):
  Cannot find 'dtc' program.
Call Stack....

**Comment by darrenrhea** [comment]
At least on Ubuntu 18.04 this might work:

```bash
sudo apt install device-tree-compiler
$ type dtc
dtc is /usr/bin/dtc
```

**Comment by matthew-renodin** [comment]
Yes, this was the issue!!!

**Comment by kent-mcleod** [comment]
I updated https://docs.sel4.systems/HostDependencies.html with dtc now.

**Comment by kent-mcleod** [comment]
Thanks for reporting!
